# data :
#   name: SHOMRI 
#   data_dir: /projects/prjs1633/anomaly_detection/SHOMRI/
#   category: test
#   image_size: 128 
#   batch_size: 1
#   mask : True 
#   imput_channel : 1 

# model:
#   checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI  
#   resnet: resnet50
#   weight_decay: 0.05 
#   ckpt : 600 
#   eta : 7
  
#   w_mask : 0
#   w : 100
#   diffusion_steps: 1000
#   mask_steps: 200
#   test_steps: 200 
#   skip : 20   
#   skip_mask: 20
#   mask0_thresholds: 0.08
#   mask_repeat : 1
#   test_repeat : 1



data:
  name: 'SHOMRI'
  data_dir: '/projects/prjs1633/anomaly_detection/SHOMRI/'
  category: 'default_only_train'
  patch_size: [64, 64, 64] 
  patches_per_volume: 4
  image_size: 64 
  imput_channel: 1
  batch_size: 8
  
  inference_stride: [64, 64, 64] 
  inference_patch_batch_size: 8

  save_dir: /projects/prjs1633/evaluation_results
  
model:
  device: 'cuda'
  checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI  
  resnet: resnet50
  weight_decay: 0.05 
  ckpt : 400 
  eta : 7
  num_workers: 4

  beta_start: 0.0001
  beta_end: 0.008
  
  w_mask : 0
  w : 100
  diffusion_steps: 1000
  mask_steps: 200
  test_steps: 200 
  skip : 20   
  skip_mask: 20
  mask0_thresholds: 0.08
  mask_repeat : 1
  test_repeat : 1