data :
  name: SHOMRI 
  data_dir: /projects/prjs1633/anomaly_detection/SHOMRI/
  category: test
  image_size: 128 
  batch_size: 1
  mask : True 
  imput_channel : 1 

model:
  checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI  
  resnet: resnet50
  weight_decay: 0.05 
  ckpt : 600 
  eta : 7
  
  w_mask : 0
  w : 100
  diffusion_steps: 1000
  mask_steps: 200
  test_steps: 200 
  skip : 20   
  skip_mask: 20
  mask0_thresholds: 0.08
  mask_repeat : 1
  test_repeat : 1

  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cuda' 
  save_model: True
  num_workers : 8