data:
  name: 'SHOMRI'
  data_dir: '/projects/prjs1633/anomaly_detection/SHOMRI/'
  category: 'testStep200_w100' #"run_check" #
  
  # Training patches
  image_size: 128
  patch_size: [64, 64, 64]
  patches_per_volume: 4
  batch_size: 4
  imput_channel: 1
  
  # Inference settings
  inference_stride: [32, 32, 32]  # 50% overlap for better reconstruction
  inference_patch_batch_size: 16
  
model:
  device: 'cuda'
  epochs: 300
  epochs_checkpoint: 20
  eval_frequency: 10  # Evaluate more frequently in early training
  resnet: resnet50
  
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_workers: 4
  
  # Diffusion parameters
  diffusion_steps: 1000
  beta_start: 0.0001
  beta_end: 0.008
  eta : 1
  
  # Inference parameters
  test_steps: 200
  skip: 20
  test_repeat: 5  
  mask_steps: 50        # smaller than test_steps; 0 = disable masking
  skip_mask: 10
  w_mask: 10              # guidance scale for stage 1
  w: 100
  mask_repeat: 1
  mask0_thresholds: 0.15  # lambda in Eq. 20; tune between 0.3-0.7

  checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI
  ckpt: 100
