# data :
#   name: SHOMRI 
#   data_dir: /projects/prjs1633/anomaly_detection/SHOMRI/
#   category: test
#   image_size: 128 
#   batch_size: 1
#   mask : False 
#   imput_channel : 1

# model:
#   checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI
#   resnet: resnet50
#   learning_rate: 3e-4 
#   weight_decay: 0.05 
#   epochs: 2000 
#   epochs_checkpoint: 100
#   diffusion_steps: 1000
#   beta_start : 0.0001
#   beta_end : 0.02 
#   device: 'cuda'
#   num_workers : 8


data:
  name: 'SHOMRI'
  data_dir: '/projects/prjs1633/anomaly_detection/SHOMRI/'
  category: 'hip' 
  image_size: 128 
  patch_size: [32, 32, 32]  #
  patches_per_volume: 4
  imput_channel: 1
  batch_size: 1  
  
model:
  device: 'cuda'
  learning_rate: 0.0001
  weight_decay: 0.0
  num_workers: 4
  epochs: 1000
  epochs_checkpoint: 50
  diffusion_steps: 1000
  beta_start : 0.0001
  beta_end : 0.02 
  checkpoint_dir: /projects/prjs1633/checkpoints/SHOMRI